# Generated by Django 6.0.8 on 2026-08-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_alter_journey_crew_alter_ticket_journey_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["journey", "cargo", "seat"]},
        ),
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
