# Generated by Django 6.0.8 on 2026-08-10 20:37

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_alter_ticket_options_alter_station_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=station.models.train_image_path_maker
            ),
        ),
    ]
