# Generated by Django 6.0.8 on 2026-08-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0004_train_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
