# Generated by Django 6.0.8 on 2026-08-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0005_alter_station_latitude_alter_station_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traintype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
